/*
    Point of Sale System Project
    Authors: Clayton Barber, Brandon Barton, Declan Brennan, Maximilian Hasselbusch, Eric Metcalf
    Last Updated: 20 November 2015
 */
package pos;

import java.sql.Connection;

public class AdminFrame extends javax.swing.JFrame {

    private Connection con;
    private Sys system;

    /**
     * Creates new form AdminFrame
     *
     * @param con
     * @param system
     */
    public AdminFrame(Connection con, Sys system) {
        this.con = con;
        this.system = system;
        initComponents();
        this.setLocationRelativeTo(null);
       
        this.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        WelcomeBanner = new javax.swing.JLabel();
        WPSBanner = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        EmployeeFunctions = new javax.swing.JPanel();
        AddEmployee = new javax.swing.JButton();
        RemoveEmployee = new javax.swing.JButton();
        EditPrivilege = new javax.swing.JButton();
        ChangePassword = new javax.swing.JButton();
        AdministrativeFunctions = new javax.swing.JPanel();
        AddItem = new javax.swing.JButton();
        RemoveItem = new javax.swing.JButton();
        EditPrice = new javax.swing.JButton();
        InventoryLevels = new javax.swing.JButton();
        SaleFunctions = new javax.swing.JPanel();
        SalesLevels = new javax.swing.JButton();
        UserScreen = new javax.swing.JButton();
        VoidTransaction = new javax.swing.JButton();
        Logout = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel5.setText("<html> <body><b>Administrative Functions</b></body> </html>");

        jButton11.setBackground(new java.awt.Color(255, 255, 204));
        jButton11.setText("Add Employee");
        jButton11.setPreferredSize(new java.awt.Dimension(133, 93));

        jButton12.setBackground(new java.awt.Color(255, 255, 204));
        jButton12.setText("Add Employee");

        jButton13.setBackground(new java.awt.Color(255, 255, 204));
        jButton13.setText("Add Employee");
        jButton13.setPreferredSize(new java.awt.Dimension(133, 93));

        jButton14.setBackground(new java.awt.Color(255, 255, 204));
        jButton14.setText("Add Employee");
        jButton14.setPreferredSize(new java.awt.Dimension(133, 93));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(225, 225, 225))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(666, 575));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 581, -1, -1));

        jPanel3.setBackground(new java.awt.Color(180, 230, 255));

        WelcomeBanner.setText("Welcome SuperUser");

        WPSBanner.setText("                               WPS");

        jPanel2.setBackground(new java.awt.Color(180, 230, 255));
        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        EmployeeFunctions.setBackground(new java.awt.Color(180, 230, 255));
        EmployeeFunctions.setBorder(javax.swing.BorderFactory.createTitledBorder("Employee Functions"));

        AddEmployee.setBackground(new java.awt.Color(255, 255, 204));
        AddEmployee.setText("Add Employee");
        AddEmployee.setPreferredSize(new java.awt.Dimension(133, 93));
        AddEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEmployeeActionPerformed(evt);
            }
        });

        RemoveEmployee.setBackground(new java.awt.Color(255, 255, 204));
        RemoveEmployee.setText("Remove Employee");
        RemoveEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveEmployeeActionPerformed(evt);
            }
        });

        EditPrivilege.setBackground(new java.awt.Color(255, 255, 204));
        EditPrivilege.setText("Edit Privilege");
        EditPrivilege.setPreferredSize(new java.awt.Dimension(133, 93));
        EditPrivilege.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditPrivilegeActionPerformed(evt);
            }
        });

        ChangePassword.setBackground(new java.awt.Color(255, 255, 204));
        ChangePassword.setText("Change Password");
        ChangePassword.setPreferredSize(new java.awt.Dimension(133, 93));
        ChangePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChangePasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EmployeeFunctionsLayout = new javax.swing.GroupLayout(EmployeeFunctions);
        EmployeeFunctions.setLayout(EmployeeFunctionsLayout);
        EmployeeFunctionsLayout.setHorizontalGroup(
            EmployeeFunctionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeFunctionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RemoveEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EditPrivilege, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ChangePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        EmployeeFunctionsLayout.setVerticalGroup(
            EmployeeFunctionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeFunctionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EmployeeFunctionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ChangePassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EditPrivilege, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RemoveEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
        );

        AdministrativeFunctions.setBackground(new java.awt.Color(180, 230, 255));
        AdministrativeFunctions.setBorder(javax.swing.BorderFactory.createTitledBorder("Administrative Functions"));

        AddItem.setBackground(new java.awt.Color(255, 255, 204));
        AddItem.setText("Add Item");
        AddItem.setPreferredSize(new java.awt.Dimension(133, 93));
        AddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddItemActionPerformed(evt);
            }
        });

        RemoveItem.setBackground(new java.awt.Color(255, 255, 204));
        RemoveItem.setText("Remove Item");
        RemoveItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveItemActionPerformed(evt);
            }
        });

        EditPrice.setBackground(new java.awt.Color(255, 255, 204));
        EditPrice.setText("Edit Price");
        EditPrice.setPreferredSize(new java.awt.Dimension(133, 93));
        EditPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditPriceActionPerformed(evt);
            }
        });

        InventoryLevels.setBackground(new java.awt.Color(255, 255, 204));
        InventoryLevels.setText("Inventory Levels");
        InventoryLevels.setPreferredSize(new java.awt.Dimension(133, 93));
        InventoryLevels.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InventoryLevelsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AdministrativeFunctionsLayout = new javax.swing.GroupLayout(AdministrativeFunctions);
        AdministrativeFunctions.setLayout(AdministrativeFunctionsLayout);
        AdministrativeFunctionsLayout.setHorizontalGroup(
            AdministrativeFunctionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdministrativeFunctionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RemoveItem, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EditPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(InventoryLevels, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AdministrativeFunctionsLayout.setVerticalGroup(
            AdministrativeFunctionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AdministrativeFunctionsLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(AdministrativeFunctionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InventoryLevels, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EditPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RemoveItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        SaleFunctions.setBackground(new java.awt.Color(180, 230, 255));
        SaleFunctions.setBorder(javax.swing.BorderFactory.createTitledBorder("Sale Functions"));

        SalesLevels.setBackground(new java.awt.Color(255, 255, 204));
        SalesLevels.setText("Sales Levels");
        SalesLevels.setPreferredSize(new java.awt.Dimension(133, 93));
        SalesLevels.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalesLevelsActionPerformed(evt);
            }
        });

        UserScreen.setBackground(new java.awt.Color(255, 255, 204));
        UserScreen.setText("User Screen");
        UserScreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserScreenActionPerformed(evt);
            }
        });

        VoidTransaction.setBackground(new java.awt.Color(255, 255, 204));
        VoidTransaction.setText("Void Transaction");
        VoidTransaction.setPreferredSize(new java.awt.Dimension(133, 93));
        VoidTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoidTransactionActionPerformed(evt);
            }
        });

        Logout.setBackground(new java.awt.Color(204, 204, 204));
        Logout.setText("Logout");
        Logout.setPreferredSize(new java.awt.Dimension(133, 93));
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SaleFunctionsLayout = new javax.swing.GroupLayout(SaleFunctions);
        SaleFunctions.setLayout(SaleFunctionsLayout);
        SaleFunctionsLayout.setHorizontalGroup(
            SaleFunctionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SaleFunctionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SalesLevels, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UserScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VoidTransaction, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SaleFunctionsLayout.setVerticalGroup(
            SaleFunctionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SaleFunctionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SaleFunctionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VoidTransaction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UserScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SalesLevels, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(EmployeeFunctions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AdministrativeFunctions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SaleFunctions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(EmployeeFunctions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AdministrativeFunctions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SaleFunctions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(WelcomeBanner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(WPSBanner, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WelcomeBanner, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(WPSBanner))
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 717, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        this.dispose();
        system.logout();
    }//GEN-LAST:event_LogoutActionPerformed

    private void UserScreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserScreenActionPerformed
        this.dispose();
        PointofSale.doWork();
    }//GEN-LAST:event_UserScreenActionPerformed

    private void AddEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEmployeeActionPerformed
        system.addEmployee();
    }//GEN-LAST:event_AddEmployeeActionPerformed

    private void RemoveEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveEmployeeActionPerformed
        system.removeEmployee();
    }//GEN-LAST:event_RemoveEmployeeActionPerformed

    private void EditPrivilegeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditPrivilegeActionPerformed
        system.editManPrivilege();
    }//GEN-LAST:event_EditPrivilegeActionPerformed

    private void ChangePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangePasswordActionPerformed
        system.changePassword();
    }//GEN-LAST:event_ChangePasswordActionPerformed

    private void AddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddItemActionPerformed
        system.addItem();
    }//GEN-LAST:event_AddItemActionPerformed

    private void InventoryLevelsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InventoryLevelsActionPerformed
        system.InventoryLevels();
    }//GEN-LAST:event_InventoryLevelsActionPerformed

    private void RemoveItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveItemActionPerformed
        system.removeItem();
    }//GEN-LAST:event_RemoveItemActionPerformed

    private void EditPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditPriceActionPerformed
        system.editPrice();
    }//GEN-LAST:event_EditPriceActionPerformed

    private void SalesLevelsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalesLevelsActionPerformed
        system.viewSales();
    }//GEN-LAST:event_SalesLevelsActionPerformed

    private void VoidTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoidTransactionActionPerformed
        system.voidTransaction();
    }//GEN-LAST:event_VoidTransactionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddEmployee;
    private javax.swing.JButton AddItem;
    private javax.swing.JPanel AdministrativeFunctions;
    private javax.swing.JButton ChangePassword;
    private javax.swing.JButton EditPrice;
    private javax.swing.JButton EditPrivilege;
    private javax.swing.JPanel EmployeeFunctions;
    private javax.swing.JButton InventoryLevels;
    private javax.swing.JButton Logout;
    private javax.swing.JButton RemoveEmployee;
    private javax.swing.JButton RemoveItem;
    private javax.swing.JPanel SaleFunctions;
    private javax.swing.JButton SalesLevels;
    private javax.swing.JButton UserScreen;
    private javax.swing.JButton VoidTransaction;
    private javax.swing.JLabel WPSBanner;
    private javax.swing.JLabel WelcomeBanner;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    // End of variables declaration//GEN-END:variables
}
