/*
    Point of Sale System Project
    Authors: Clayton Barber, Brandon Barton, Declan Brennan, Maximilian Hasselbusch, Eric Metcalf
    Last Updated: 20 November 2015
 */
package pos;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFrame;

public class RemoveEmployeeInfo extends javax.swing.JFrame {

    Connection con;

    /**
     * Creates new form RemoveEmployeeInfo
     *
     * @param con
     */
    public RemoveEmployeeInfo(Connection con) {
        this.con = con;
        initComponents();
        this.setLocationRelativeTo(null);
            this.setVisible(true);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ETRFrame = new javax.swing.JPanel();
        ID = new javax.swing.JTextField();
        EIDLabel = new javax.swing.JLabel();
        ENameLabel = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        Submit = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("RemoveEmployeeInfo");

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));

        jLabel1.setText("Remove Employee");

        jLabel2.setText("WPS");

        ETRFrame.setBackground(new java.awt.Color(0, 0, 255));
        ETRFrame.setBorder(javax.swing.BorderFactory.createTitledBorder("Employee To Remove"));

        EIDLabel.setText("Employee ID*");

        ENameLabel.setText("Employee Name*");

        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ETRFrameLayout = new javax.swing.GroupLayout(ETRFrame);
        ETRFrame.setLayout(ETRFrameLayout);
        ETRFrameLayout.setHorizontalGroup(
            ETRFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ETRFrameLayout.createSequentialGroup()
                .addGroup(ETRFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ID)
                    .addGroup(ETRFrameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ETRFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ETRFrameLayout.createSequentialGroup()
                                .addGroup(ETRFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EIDLabel)
                                    .addComponent(ENameLabel))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(Name))))
                .addContainerGap())
            .addGroup(ETRFrameLayout.createSequentialGroup()
                .addComponent(Cancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                .addComponent(Submit))
        );
        ETRFrameLayout.setVerticalGroup(
            ETRFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ETRFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EIDLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ENameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(ETRFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Submit)
                    .addComponent(Cancel)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ETRFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ETRFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        String eid = ID.getText();
        String name = Name.getText();
        if (!checkString(eid)) {
            ID.setText("InvalidID.");
        } else if (name.equals("")) {
            ID.setText("Invalid Input");
            Name.setText("Name required");
        } else {
            try {
                Statement s = con.createStatement();
                ResultSet result = s.executeQuery("select * from EMPLOYEE where EID = '" + eid + "' and NAME = '" + name + "'");
                if (!result.next()) {
                    ID.setText("Invalid: No such employee found");
                } else {
                    Statement rs = con.createStatement();
                    rs.executeUpdate("delete from EMPLOYEE where EID = '" + eid + "'");
                    this.dispose();
                    UpdateSuccessful updateSuccessful = new UpdateSuccessful();
                }
            } catch (SQLException sqe) {
                System.err.println("Unable to delete employee");
                System.err.println(sqe.getMessage());
            }

        }
    }//GEN-LAST:event_SubmitActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JLabel EIDLabel;
    private javax.swing.JLabel ENameLabel;
    private javax.swing.JPanel ETRFrame;
    private javax.swing.JTextField ID;
    private javax.swing.JTextField Name;
    private javax.swing.JButton Submit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private boolean checkString(String eid) {
        if (eid.isEmpty()) {
            return false;
        }
        for (int i = 0; i < eid.length(); i++) {
            if (i == 0 && eid.charAt(i) == '-') {
                if (eid.length() == 1) {
                    return false;
                } else {
                    continue;
                }
            }
            if (Character.digit(eid.charAt(i), 10) < 0) {
                return false;
            }
        }
        return true;
    }
}
