/*
    Point of Sale System Project
    Authors: Clayton Barber, Brandon Barton, Declan Brennan, Maximilian Hasselbusch, Eric Metcalf
    Last Updated: 20 November 2015
 */
package pos;

import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import javax.swing.*;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

public class SalesFrame extends javax.swing.JFrame {

    Connection con;

    /**
     * Creates new form InventoryLevels
     *
     * @param con
     */
    public SalesFrame(Connection con) {
        int snum = 0;
        try {
            Statement s = con.createStatement();
            ResultSet result = s.executeQuery("select count(*) from pos.orders");
            result.next();
            snum = result.getInt(1);
            sales = new String[snum][];
            for (int i = 0; i < snum; i++) {
                sales[i] = new String[5];
            }
            Statement s1 = con.createStatement();
            ResultSet result1 = s1.executeQuery("select * from pos.orders order by -oid");
            for (int i = 0; result1.next(); i++) {
                sales[i][0] = String.valueOf(result1.getInt(1)); //oid
                sales[i][1] = String.valueOf(result1.getString(2)); //eid
                sales[i][2] = String.valueOf(result1.getDate(3)); //date
                sales[i][3] = String.valueOf(result1.getBigDecimal(4)); //tax
                sales[i][4] = String.valueOf(result1.getDouble(5)); //total
            }

        } catch (SQLException sql) {
            System.err.println("Error fetching sales data from pos.orders");
        }
        this.con = con;
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setVisible(true);
    }

    private void Search(ActionEvent e)  {
        String order = OrderID.getText();
        String emp = EmpID.getText();
        String date = Date.getText();
        List<RowFilter<Object, Object>> filters = new ArrayList<>(3);
        if (!order.isEmpty()) {
            filters.add(RowFilter.regexFilter("(?i)" + order, 0));
        }
        if (!emp.isEmpty())    {
            filters.add(RowFilter.regexFilter("(?i)" + emp, 1));
        }
        if (!date.isEmpty())    {
            filters.add(RowFilter.regexFilter("(?i)" + date, 2));
        }
        RowFilter rf = RowFilter.andFilter(filters);
        rowSorter.setRowFilter(rf);
        return;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        SalesTable = new javax.swing.JTable(sales, columnNames);
        Done = new javax.swing.JButton();
        SalesTable.setAutoCreateRowSorter(true);
        rowSorter = new TableRowSorter<>(SalesTable.getModel());
        SalesTable.setRowSorter(rowSorter);

        filter = new javax.swing.JPanel();
        Search = new javax.swing.JButton();
        IOL = new javax.swing.JLabel();
        OrderID = new javax.swing.JTextField();
        IEL = new javax.swing.JLabel();
        EmpID = new javax.swing.JTextField();
        IDL = new javax.swing.JLabel();
        Date = new javax.swing.JTextField();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(180, 230, 255));

        jLabel1.setText("Sales Data");

        jLabel2.setText("WPS");

        jPanel1.setBackground(new java.awt.Color(180, 230, 255));

        filter.setBackground(new java.awt.Color(180,230,255));

        IOL.setText("Order ID: ");

        IEL.setText("Employee ID: ");

        IDL.setText("Date: ");

        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search(evt);
            }
        });

        jScrollPane1.setViewportView(SalesTable);

        Done.setText("Done");
        Done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Done))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 619, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Done))
        );
        javax.swing.GroupLayout filterLayout = new javax.swing.GroupLayout(filter);
        filter.setLayout(filterLayout);
        filterLayout.setHorizontalGroup(
                filterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(filterLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(IOL)
                                .addComponent(OrderID)
                                .addComponent(IEL)
                                .addComponent(EmpID)
                                .addComponent(IDL)
                                .addComponent(Date)
                                .addComponent(Search))
                        .addGap(0,0, Short.MAX_VALUE)
        );
        filterLayout.setVerticalGroup(
                filterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(filterLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(filterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(IOL)
                                        .addComponent(OrderID)
                                        .addComponent(IEL)
                                        .addComponent(EmpID)
                                        .addComponent(IDL)
                                        .addComponent(Date)
                                        .addComponent(Search))
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(9, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(filter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(17, 17, 17))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(filter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoneActionPerformed
        this.dispose();
    }//GEN-LAST:event_DoneActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Done;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable SalesTable;
    private String sales[][];
    private String columnNames[] = {"Order ID", "Employee ID", "Date", "Tax Rate", "Total"};
    // filter results
    private javax.swing.JPanel filter;
    private javax.swing.JButton Search;
    private javax.swing.JLabel IOL;
    private javax.swing.JTextField OrderID;
    private javax.swing.JLabel IEL;
    private javax.swing.JTextField EmpID;
    private  javax.swing.JLabel IDL;
    private javax.swing.JTextField Date;
    private TableRowSorter<TableModel> rowSorter;
    // End of variables declaration//GEN-END:variables
}
