/*
    Point of Sale System Project
    Authors: Clayton Barber, Brandon Barton, Declan Brennan, Maximilian Hasselbusch, Eric Metcalf
    Last Updated: 20 November 2015
 */
package pos;

import java.lang.*;
import java.io.*;
import java.sql.*;
import javax.swing.JFrame;

public class SysFrame extends javax.swing.JFrame {

    private Connection con;
    private Sys system;
    boolean isNewTransaction = true;
    PrintStream ps;
    RemoveItem ri;
    AddItem ai;
    EditItemPrice eip;
    NewReturn nr;
    ManagerLogin ml;
    CashorCredit coc;

    /**
     * Creates new form SysFrame
     *
     * @param con
     * @param system
     */
    public SysFrame(Connection con, Sys system) {
        this.con = con;
        this.system = system;
        initComponents();
        if (!PointofSale.system.isManager)  {
            Exit.setVisible(false);
        }
        this.setLocationRelativeTo(null);
        ps = new PrintStream(new COS(jTextArea1));
        System.setOut(ps);
        //System.setErr(ps);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Return = new javax.swing.JButton();
        AddItem = new javax.swing.JButton();
        EditItem = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        RemoveItem = new javax.swing.JButton();
        Checkout = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jButton5.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("POS");
        setBackground(new java.awt.Color(255, 255, 204));
        setForeground(new java.awt.Color(255, 255, 204));

        jPanel2.setBackground(new java.awt.Color(180, 230, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 204));
        String mode;
        if(system.isManager) mode = "Manager Mode";
        else mode = "Employee Mode";
        jLabel1.setText(mode + ": " + system.name + " " + system.eid);

        Return.setText("Rental Return");
        Return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnActionPerformed(evt);
            }
        });

        EditItem.setText("Edit Item Price");
        EditItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEditItemActionPerformed(evt);
            }
        });
        Exit.setText("Cancel");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        AddItem.setText("Add Item");
        AddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddItemActionPerformed(evt);
            }
        });

        RemoveItem.setText("Remove Item");
        RemoveItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveItemActionPerformed(evt);
            }
        });

        Checkout.setText("Checkout");
        Checkout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckoutActionPerformed(evt);
            }
        });

        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(180, 230, 255));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Return, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Checkout, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(RemoveItem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AddItem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EditItem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Exit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(AddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RemoveItem, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Checkout, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Return, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EditItem, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RemoveItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveItemActionPerformed
        if((ai == null || !ai.isDisplayable()) && (eip == null || !eip.isDisplayable()) && (ml == null || !ml.isDisplayable()) && (ri == null || !ri.isDisplayable()) && (nr == null || !nr.isDisplayable()) && (coc == null ||!coc.isDisplayable())) {
            if( system.s == null || system.s.l == null ||system.s.l.head == null){
                jTextArea1.setText("");
                System.out.println("There is no transaction in progress.");
            }
            else {
                jTextArea1.setText("");
                ri = new RemoveItem(system.s, ps);
            }
        }
    }//GEN-LAST:event_RemoveItemActionPerformed

    private void AddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddItemActionPerformed
        // TODO add your handling code here:
        if((ai == null || !ai.isDisplayable()) && (eip == null || !eip.isDisplayable()) && (ml == null || !ml.isDisplayable()) && (ri == null || !ri.isDisplayable()) && (nr == null || !nr.isDisplayable()) && (coc == null ||!coc.isDisplayable())) {
            if (system.s == null || system.s.l == null || system.s.l.head == null) {
                jTextArea1.setText("");
                system.buildSale();
                ai = new AddItem(system.s, ps);
                //System.out.println(system.s);
            } else {
                jTextArea1.setText("");
                //System.out.println(system.s);
                ai = new AddItem(system.s, ps);
            }
        }

    }//GEN-LAST:event_AddItemActionPerformed
    private void AddEditItemActionPerformed(java.awt.event.ActionEvent evt){
        if((ai == null || !ai.isDisplayable()) && (eip == null || !eip.isDisplayable()) && (ml == null || !ml.isDisplayable()) && (ri == null || !ri.isDisplayable()) && (nr == null || !nr.isDisplayable()) && (coc == null ||!coc.isDisplayable())) {
            if (system.s != null && system.s.l != null && system.s.l.head != null) {
                jTextArea1.setText("");
                if(system.isManager){
                    eip = new EditItemPrice(system.s, ps);
                }
                else{
                    ml = new ManagerLogin(system.s, ps);
                }
            }
            else{
                jTextArea1.setText("");
                System.out.println("There is no transaction in progress.");
            }
        }
    }

    private void CheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckoutActionPerformed
        if((ai == null || !ai.isDisplayable()) && (eip == null || !eip.isDisplayable()) && (ml == null || !ml.isDisplayable()) && (ri == null || !ri.isDisplayable()) && (nr == null || !nr.isDisplayable()) && (coc == null ||!coc.isDisplayable())) {
            /*brute force way of checking if their shopping cart is empty...*/
            if(system.s != null && system.s.l != null && system.s.l.head != null) {
                jTextArea1.setText("");
                coc = new CashorCredit(system.s, ps, this);
                isNewTransaction = true;
            }
            else{
                jTextArea1.setText("");
                System.out.println("There is no transaction in progress.");
            }
            system.buildSale();
        }
    }//GEN-LAST:event_CheckoutActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        if((ai == null || !ai.isDisplayable()) && (eip == null || !eip.isDisplayable()) && (ml == null || !ml.isDisplayable()) && (ri == null || !ri.isDisplayable()) && (nr == null || !nr.isDisplayable()) && (coc == null ||!coc.isDisplayable())) {
            //nullify sale if employee/manager logs out in the middle of a transaction
            system.s = null;
            this.dispose();
            system.logout();
        }
    }//GEN-LAST:event_LogoutActionPerformed

    private void ReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnActionPerformed
        if((ai == null || !ai.isDisplayable()) && (eip == null || !eip.isDisplayable()) && (ml == null || !ml.isDisplayable()) && (ri == null || !ri.isDisplayable()) && (nr == null || !nr.isDisplayable()) && (coc == null ||!coc.isDisplayable())) {
            //nr = new NewReturn(this, system, con);
        }
    }//GEN-LAST:event_ReturnActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnActionPerformed
        this.dispose();
        AdminFrame af = new AdminFrame(con, system);
    }//GEN-LAST:event_ReturnActionPerformed

    public void setOutputText(String s) {
        jTextArea1.setText(s);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddItem;
    private javax.swing.JButton EditItem;
    private javax.swing.JButton Exit;
    private javax.swing.JButton Checkout;
    private javax.swing.JButton Logout;
    private javax.swing.JButton RemoveItem;
    private javax.swing.JButton Return;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
